name: "Trigger release manually"

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install cargo-bump
        run: cargo install cargo-bump

      - name: Bump version
        run: cargo bump patch

      - name: install cargo-get
        run: cargo install cargo-get

      - name: commit changes
        run: |
          git config --global user.name 'windpress'
          git config --global user.email 'windpress@users.noreply.github.com'
          git commit -am "Bump version to $(cargo get package.version)"
          git push

      - name: tag
        run: |
          git tag $(cargo get package.version)
          git push origin $(cargo get package.version)
